name: test mcp server

on:
  pull_request:
    types: [labeled]
    branches:
      - main
    paths:
      - mcp_server/src/t2c_mcp.py

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13" # try 3.12 if pytest/ ruff give error 

      - name: install package and dev dependencies
        run: pip install -e ".[dev]"
        working-directory: mcp_server

      - name: lint with ruff
        run: ruff check mcp_server/src/t2c_mcp.py

      # - name: run tests  # no tests yet; pytest exits code 5 on empty file
      #   run: pytest mcp_server/tests/test_t2c_mcp.py